apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prom-node-exporter
  labels:
    app.kubernetes.io/name: prom
    app.kubernetes.io/component: node-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prom
      app.kubernetes.io/component: node-exporter

  template:
    metadata:
      app.kubernetes.io/name: prom
      app.kubernetes.io/component: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.12.1
          imagePullPolicy: IfNotPresent

          ports:
            - name: http
              containerPort: 9100

          # TODO: these need to be set across the observability stack
          # resources:
          #   requests:
          #     cpu: 10m
          #     memory: 32Mi
          #   limits:
          #     cpu: 100m
          #     memory: 128Mi

          securityContext:
            readOnlyRootFilesystem: true
            # "Often required to read protected files like /sys/class/dmi/id/*"
            #   ~ Gemini and someone on discuss.prometheus.io
            runAsNonRoot: false
            runAsUser: 0

      # Run on control-plane nodes too
      tolerations:
        - key: "components.gke.io/gke-managed-components"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
