skip-check:
  # This is a lab project; we have no plans to enable VPC flow logs at present
  - CKV_GCP_26
  # The network stack only defines the network topology for our environment-it has
  # no opinion about traffic patterns (we leave this to the downstream stacks)
  - CKV2_GCP_18
