loki:
  auth_enabled: false

  commonConfig:
    replication_factor: 1

  storage:
    type: gcs

    bucketNames:
      chunks: lab-platform-loki-bucket-926557058358
      ruler: lab-platform-loki-bucket-926557058358

    gcs:
      # Nothing credential-related here if using GKE Workload Identity
      # The chart's GCS client will use Google credentials available to the Pod.

  schemaConfig:
    configs:
      - from: "2026-01-01"
        store: tsdb
        object_store: gcs
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

serviceAccount:
  create: true
  name: loki
  annotations:
    iam.gke.io/gcp-service-account: observability-loki@gke-platform-lab.iam.gserviceaccount.com

deploymentMode: Monolithic

singleBinary:
  replicas: 1

defaults:
  tolerations:
    - key: "components.gke.io/gke-managed-components"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

chunksCache:
  enabled: false

resultsCache:
  enabled: false

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomPlanner:
  replicas: 0
bloomBuilder:
  replicas: 0
bloomGateway:
  replicas: 0
