apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sts.yml
  - svc.yml
  - rbac.yml
  - node-exporter/ds.yml

configMapGenerator:
  - name: prom-cm
    files:
      - prometheus.yml
