apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deploy.yml
  - svc.yml
  - pvc.yml

configMapGenerator:
  - name: graf-ds-cm
    files:
      - datasource-loki.yml
      - datasource-prom.yml

  - name: graf-dash-cm
    files:
      - dashboards-cluster-health.json
      - dashboards-default.yml
