apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: {{ .Values.namespaces.app }}
  finalizers:
    # Foreground cascading deletion (delete dependencies then delete App)
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "observability.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: alloy
spec:
  project: {{ default .Values.project "default" }}
  sources:
    - repoURL: ghcr.io/grafana/helm-charts
      chart: alloy
      targetRevision: 1.11.1
      helm:
        valueFiles:
          - $gke-platform-lab/observability/alloy/values.yml

    - repoURL: https://github.com/MrHachi/gke-platform-lab.git
      targetRevision: {{ default "main" .Values.alloy.targetRevision }}
      ref: gke-platform-lab

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.namespaces.component }}

  # Extra information to show in the Argo CD Application details tab
  info:
    - name: "Alloy:"
      value: "https://TODO.todo"

  syncPolicy:
    automated:
      enabled: true
      prune: true # Delete resources no longer in git (if false these are orphaned if not found)
      selfHeal: true
      allowEmpty: false

    # Retry with exponential backoff settings
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m

  revisionHistoryLimit: 10
