skip-check:
  # Private cluster/nodes:
  # NAT is out of scope for this lab project-clusters and nodes
  # will instead be protected with firewalls
  - CKV_GCP_25
  - CKV_GCP_64
  # Master authorized networks:
  # I lack a stable public IP and this is a lab project
  - CKV_GCP_20
  # Google groups integration:
  # Out of scope for this lab project; environment not a part of any organizations
  - CKV_GCP_65
  # Binary auth:
  # Out of scope for this lab project
  - CKV_GCP_66
  # Metadata server:
  # This should be enabled; this check appears broken
  - CKV_GCP_69
  # GCS bucket versioning:
  # Out of scope for this lab project; we don't care if Loki's data disappears here
  - CKV_GCP_78
  # GCS bucket access logging:
  # Out of scope for this lab project
  - CKV_GCP_62
  # GCS bucket log-to-self:
  # Checkov thinks this bucket is sending access logs to itself
  # It is not
  - CKV_GCP_63
  # ADR003
  - CKV_GCP_8
  # ADR004
  - CKV_GCP_1
