name: TF Stack Deploy

on:
  push:
    tags:
      - platform/v**

concurrency:
  group: tf-stack-cd
  cancel-in-progress: false

env:
  TOFU_VERSION: 1.12.0
  STACK_DIR: infrastructure/stacks

jobs:
  execute-platform-plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        working-directory: ${{ env.STACK_DIR }}/platform
    env:
      PLAN_FILENAME: "${{ github.sha }}.tfplan"
      PLAN_BUCKET: ${{ vars.TFSTATE_BUCKET }}
      ARTIFACT_PREFIX: "${{ vars.ARTIFACT_PREFIX }}"
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Authenticate with GCP for artifact retrieval
        uses: google-github-actions/auth@v3
        with:
          project_id: "${{ vars.GCLOUD_PROJECT }}"
          workload_identity_provider: "${{ vars.GCLOUD_PROVIDER }}"
          service_account: "${{ vars.ARTIFACT_SA }}"

      - name: Download plan
        run: gcloud storage cp "gs://${PLAN_BUCKET}/${ARTIFACT_PREFIX}cd/platform/${PLAN_FILENAME}" "${PLAN_FILENAME}"

      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v2
        with:
          tofu_version: ${{ env.TOFU_VERSION }}

      - name: Authenticate with GCP for deployment
        uses: google-github-actions/auth@v3
        with:
          project_id: "${{ vars.GCLOUD_PROJECT }}"
          workload_identity_provider: "${{ vars.GCLOUD_PROVIDER }}"
          service_account: "${{ vars.APPLY_SA }}"

      - name: Initialize stack online
        run: tofu init

      - name: Execute the plan file
        run: tofu apply -auto-approve -input=false "${PLAN_FILENAME}"
